name: Build and Sign Android System Image

on:
  push:
    branches:
      - main # Или любая другая ветка, где вы хотели бы запускать этот workflow.
    tags:
      - 'v*' # Раскомментируйте, если хотите запускать workflow на тегах

jobs:
  sign_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Установка зависимостей (например, avbtool и т.д.)
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk-libsparse-utils

    # Добавьте ваш шелл-скрипт, который нужно выполнить
    - name: Run signing script
      run: |
        # Ваш sh-скрипт здесь
        # Например, если ваш скрипт сохранён в репозитории под именем sign-image.sh:
        git clone https://github.com/Veynamer/sgsi_signer-AVB sign-avb -b main
        chmod +x ./sign-avb/sign-image.sh
        ./sign-avb/sign-image.sh

    # Опционально, вы можете загружать подписанный образ на GitHub Artifacts или в релиз
    - name: Upload signed image
      uses: actions/upload-artifact@v2
      with:
        name: signed-image
        path: signed_*.img
